config/routes.rb
Rails.application.routes.draw do



root to: 'pages#index'




  get '/profil', to: 'users#edit', as: :profil
  get '/class/:slug', to: 'posts#categories', as: :categories_posts
  patch '/profil', to: 'users#update'



  #Session

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' , as: :destroy_session


  resources :posts do

  collection do

    get 'me'

  end

  end

  resources :passwords, only: [:new, :create, :edit, :update]
  resources :games do

  resource :subscriptions, only: [:create, :destroy]

  end

  resources :users, only: [:new, :create, :edit] do

    member do
      get 'confirm'

end
end

scope 'superadmin', module: 'admin', as: 'admin' do
resources :categories, except: [:show]




end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :category, counter_cache: true
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user




validates :title, :test , :release_date, presence: true
validates :avatar_file, presence: true, on: :create
validate :release_date_not_future


has_image :avatar
has_and_belongs_to_many :posts


  after_destroy :destroy_posts


def release_date_not_future

  if release_date.present? && release_date.future?
    errors.add(:release_date,'you cannot give your opinion on a game that has not yet been released')
  end
end


def followedBy?(user)

  subscriptions.where(user_id: user.id).count > 0 if user.respond_to? :id

  end



private

def destroy_posts

   Post.find_by_sql('SELECT * FROM posts LEFT JOIN games_posts ON games_posts.post_id = posts.id WHERE games_posts.post_id IS NULL').each do |post|

   post.destroy

     end
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController


 before_action :set_game, only: [:edit, :update, :destroy]
 skip_before_action :only_signed_in, only: [:show]

def index

 @games = current_user.games

end

def show

@game = Game.find(params[:id])

end


def new

@game  = current_user.games.new

  end

  def create

  @game = current_user.games.new(game_params)

  if @game.save
    redirect_to games_path, success: 'thank you for sharing with us your passion for video games'
  else
    render :new
  end
end

def edit

end

def update

 if @game.update(game_params)
redirect_to games_path, success: 'Your Favorite game has been updated'

else

  render :edit

 end

  end


  def destroy


 @game.destroy

redirect_to games_path, success: 'Your Favorite game has been deleted'

  end

  private


  def game_params

   params.require(:game).permit(:title, :test, :release_date, :category_id, :avatar_file)

  end


  def set_game

  @game = current_user.games.find(params[:id])

  end

end

app/views/games/_form.html.erb
<%= form_for game, html: {class: 'form-horizontal'} do |f| %>

<% if game.errors.any? %>

<div class="alert alert-danger">

<ul>

<% game.errors.full_messages.each do |message| %>
<li> <%= message %> </li>

<% end %>

</ul>
</div>
<% end %>


 <div class="form-group">

  <%= f.label :title, "Title", class: 'col-md-4 control-label' %>
  <div class="col-md-8">

   <%= f.text_field :title, class: 'form_control'%>

  </div>
  </div>


  <div class="form-group">

  <%= f.label :avatar_file, "Avatar", class: 'col-md-4 control-label' %>
  <div class="col-md-8">

   <%= f.file_field :avatar_file, class: 'form_control'%>

  </div>
  </div>


  <div class="form-group">

  <%= f.label :category_id, "Category", class: 'col-md-4 control-label' %>
  <div class="col-md-8">

   <%= f.select :category_id, Category.pluck(:name,  :id),{}, class: 'form_control multiple = "multiple"' %>

  </div>
  </div>


  <div class="form-group">

  <%= f.label :test, "thoughts", class: 'col-md-4 control-label' %>
  <div class="col-md-8">

   <%= f.text_area :test, class: 'form_control' %>

  </div>
  </div>

  <div class="form-group">

  <%= f.label :release_date, "Release Date", class: 'col-md-4 control-label' %>
  <div class="col-md-8">

   <%= f.text_field :release_date, class: 'form_control', data: {behavior: 'flatpickr' } %>

  </div>
  </div>




  <div class="form-group">


    <div class="col-md-offset-4 col-md-6">
      <button type="submit" class="btn btn-ghost" style="background-image: linear-gradient(to right top, #04080d, #1f2043, #681d62, #b90053, #eb1212); color: white;">
        <%= game.new_record? ? 'Add' : 'Update' %>
      </button>





    </div>
  </div>

<% end %>

app/views/games/_game.html.erb
<li class="list-group-item">

<%= link_to game do %>
  <h4 class="list-group-item-heading"><%= game.title %></h4>
  <p class="list-group-item-text"><%= truncate game.test, length: 70 %></p>
<% end %>

</li>

app/views/games/edit.html.erb
<% content_for :content do %>
<div class="panel panel-default">
  <div class = "panel-heading">Update <%= @game.title %></div>
  <div class="panel-body">
    <%= render 'form', game: @game %>
  </div>
</div>
<% end %>

<%= render template: 'layouts/profile' %>

app/views/games/index.html.erb
<% content_for :tab, :games %>

<% content_for :content do %>

<h1>Manage my games</h1>




<p class="text-right">
  <a href="<%= new_game_path%>" class="btn btn-ghost">Add Your Favorite Games</a>

</p>

<table class = "table table_striped">

  <thead>

<tr>

  <th>avatar</th>
  <th>Title</th>
  <th>Thoughts</th>
  <th>Release Date</th>
  <th>Category</th>

</tr>

</thead>

<tbody>

  <% @games.each do |game| %>

  <tr>

    <td><%= image_tag game.avatar_url %></td>
    <td><%= game.title %></td>
    <td><%= truncate game.test, length: 50 %></td>
    <td><%= game.release_date %></td>
    <td><%= game.category.name %></td>
    <td>



<%= link_to 'Show', game, class: 'btn btn-ghost' %>
</td>
<td>
<%= link_to 'Edit', [:edit,game], class: 'btn btn-gradient' %>
</td>
<td>
<%= link_to 'Delete',game, class: 'btn btn-flat', data: {method: :delete, confirm:'Do you Really Want to Delete your Favorite Game ?'} %>



    </td>
</tr>

<% end %>
</tbody>
</table>
<% end %>

<%= render template: 'layouts/profile' %>





















  </thead>

app/views/games/new.html.erb
<% content_for :content do %>
<div class="panel panel-default">
  <div class = "panel-heading">Add a New Game</div>
  <div class="panel-body">
    <%= render 'form', game: @game %>
  </div>
</div>
<% end %>

<%= render template: 'layouts/profile' %>

app/views/games/show.html.erb
<div class="row">

<div class="col-md-2">


<%= image_tag @game.avatar_url, class: 'img-circle' %>


</div>

<div class="col-md-10">


<h2> <%= @game.title %></h2>
<p><%= @game.test %></p>
<% if user_signed_in? %>
<% if @game.followedBy?(current_user) %>
<%= link_to "Unsubscribe",[@game, Subscription], method: :delete, class: 'btn btn-danger' %>
<% else %>
<%= link_to "Subscribe", [@game, Subscription], method: :post, class: 'btn btn-success' %>

<% end %>
<%end %>
<%= link_to "My Games", games_path,  class: 'btn-ghost' %>
</div>

</div>


<div class="row">




<% @game.posts.each do |post| %>

<div class="col-md-4">


<%= render post %>


</div>
<% end %>

</div>