config/routes.rb
Rails.application.routes.draw do



root to: 'pages#index'




  get '/profil', to: 'users#edit', as: :profil
  get '/class/:slug', to: 'posts#categories', as: :categories_posts
  patch '/profil', to: 'users#update'



  #Session

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' , as: :destroy_session


  resources :posts do

  collection do

    get 'me'

  end

  end

  resources :passwords, only: [:new, :create, :edit, :update]
  resources :games do

  resource :subscriptions, only: [:create, :destroy]

  end

  resources :users, only: [:new, :create, :edit] do

    member do
      get 'confirm'

end
end

scope 'superadmin', module: 'admin', as: 'admin' do
resources :categories, except: [:show]




end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="application.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,500&display=swap" rel="stylesheet">



  </head>

  <body background="https://res.cloudinary.com/dnoyrq2k1/image/upload/v1583424418/bb_uffuuj.jpg">


    <div class="navbar sticky-top navbar-inverse">
     <div class="container">
      <div class="navbar-header">
       <a href="<%= root_path %>"><img src="https://res.cloudinary.com/dnoyrq2k1/image/upload/v1582032928/Sans_titre-2_choso4.jpg" />
</a>

       </a>
      </div>


      <% if isAdmin? %>
       <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Game Management', [:admin, Category],{:style=>"left:900px;"}%>

        </li>

      </ul>

      <% end %>
        <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
         <%= current_user.username %>



         <span class="caret"></span>


            </a>
            <%= image_tag current_user.avatar_url, :class => "style_avatar_nav" %>

            <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'My Profile', profil_path %></li>
            <li><%= link_to 'Log out', destroy_session_path, data: {method: :delete} %></li>




                </ul>

              </li>




          <% else %>



        <li><a href="<%=new_user_path%>">Register</a></li>
        <li><a href="<%=new_session_path%>">Log In</a></li>
        <% end %>
      </ul>
    </div>
   </div>

   <div class="container">

    <% if flash[:success] %>

    <div class="alert alert-success" role="alert">
    <%= flash[:success] %>


      </div>

      <% end %>

      <% if flash[:danger] %>

    <div class="alert alert-danger">

      <%= flash[:danger] %>

      </div>

      <% end %>




    <%= yield %>


</div>



        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-eval': 'false', 'data-turbolinks-track': 'reload' %>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<!--          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
 -->
         <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
         <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.js"></script>




   </body>





</html>

app/views/layouts/profile.html.erb
<class class="row">

  <div class="col-md-8">


<%= yield(:content) %>

 </div>

<div class="cold-md-4">


  <div class="list-group">

<a href="<%= posts_path%>" class = "list-group-item<%=  yield(:tab)== 'posts' ? ' active': '' %>">My Favourite Games</a>
<a href="<%= me_posts_path%>" class = "list-group-item<%=  yield(:tab)== 'me' ? ' active': '' %>">My Posts</a>
<a href="<%= games_path%>" class = "list-group-item<%=  yield(:tab)== 'games' ? ' active': '' %>">My Games</a>
<a href="<%= profil_path%>" class = "list-group-item<%= yield(:tab)== 'profil' ? ' active': '' %>">My Profile</a>


     </div>
   </div>
</div>